name: PR build

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/
              
    - name: Install website dependencies
      run: cd website && yarn

    - name: Build library
      run: cd website && yarn build
